language: rust
sudo: false
rust:
 - nightly
 
cache: cargo

script:
 - cargo test --verbose

after_success: |
    [ $TRAVIS_PULL_REQUEST = false ] &&
    [ $TRAVIS_RUST_VERSION = stable ] &&
    cargo doc --no-deps &&
    ./.travis/docs.sh
